/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://qzoku6kclbcn5fjfmrdvkc2y3m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xsrng2covbc2hh6gtwhpwzdtee",
    "aws_cognito_identity_pool_id": "us-east-1:05489df5-5d3b-405e-849f-bff9b79abbc8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_y6taWA6Vb",
    "aws_user_pools_web_client_id": "11osddq7s9rttuaufmkft1tcob",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "travel34918-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
