name: CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy to Amplify
        if: success() # This step will only run if all previous steps were successful
        run: |
          npm install -g @aws-amplify/cli
          amplify configure
          amplify push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_REGION: us-east-1
